### ISSUE TITLE
Issues encrypting/decrypting

### ISSUE THREAD

**Issue by antiftw** [DoctrineEncryptBundle/DoctrineEncryptBundle#32]
Like the title says, I'm having some problems getting this bundle to work. 

I've followed the docs:

- Install using composer
- Enable bundle in bundles.php
- config.yaml: all default except ive changed this:  `secret_directory_path: '%kernel.project_dir%/config/secrets'` so thats the only uncommented line in the config file
- services.yaml : added the 4 service definitions mentioned w.r.t using Attributes instead of Annotations
- `/config/secrets/` contains `.Halite.key`
- Added the #[Encrypted] anotation to my entity:
```php
#[ORM\Column(type: 'string', length: 255,  nullable: true)]
#[Encrypted]
private ?string $clientSecret = null;
```
- Create and persist an entity: 
```php
$entity = new Entity();
$entity->setClientSecret('random_secret');
$this->em->persist($entity);
$this->em->flush();
```
- This results in the string 'random_secret' being stored plaintext in the database.
- However when I run `bin/console doctrine:encrypt:database` it does find the field, and successfully encrypts the value
- Weirdly enough the reverse operation does not work, and running `bin/console doctrine:decrypt:database`  results in this message: 

> Decrypting all fields. This can take up to several minutes depending on the database size.
>Processing App\Entity\Salesforce
>1/1 [============================] 100%
>Decryption finished values found: 1, decrypted: 0.
>All values are now decrypted.

So it does find the value to decrypt and attempts it but it seems it silently fails because the value in de Database stays the same (encrypted) value.

I was hoping anyone has any insights into what might be causing this, because I've been trying all day without any luck. I've tried being as complete as possible, but if more information is required please do not hesitate to ask.

Thanks in advance!

P.S. Of course I would prefer the automatic encryption to work, the commands was more for testing if the underlying functionality actually did something. Which seems to, for about 50% :)

**Comment by antiftw** [comment]
Okay. After a lot of trial and error and a weekend of debugging I found a solution. 

Not sure if its THE solution, but here goes:

First I tried setting up this bundle in a separate/isolated project:

- Used `dunglas/symfony-docker` to set up quick empty project. First with default settings (Symfony 7).
- Added this bundle (`composer require doctrineencryptbundle/doctrine-encrypt-bundle`).
- Created simple entity with `#[Enrypted]` property.
- Created controller to persist and load entity to check encryption lifecycle.

This worked. So I tried it with the same process, clean repo, this time Symfony 6.4.7 (almost matching the original repo's Symfony version 6.4.6). I also got this to work, while I had to add the block from the confuration to my services.yaml, switching to the AttributeReader in stead of the AnnotationReader. 

So I now know it's not your repository, and it should be able to run in a similar Symfony version using my configuration.

So this asked for a more deep dive into the workings of the bundle, and since it relies on EventSubscribers/EventListeners, a deep dive into that. So I wrote some test-code and noticed that my custom EventSubscriber was not being triggered when subscribing to the same events as this bundle does:

```php
    public function getSubscribedEvents(): array
    {
        return [
            Events::postLoad,
            Events::onFlush,
            Events::preFlush,
            Events::postFlush,
            Events::onClear,
        ];
    }
```

So I figured I'd read up a bit in the Symfony docs and found out that the [Doctrine Lifecycle Subscribers](https://symfony.com/doc/6.4/doctrine/events.html#doctrine-lifecycle-subscribers) were deprecated from Symfony  6.3. This made me take a look through the code of this bundle to see how the configuration was done internally. 

Then I found this file `doctrine-encrypt-bundle/src/Resources/config/service_listeners_with_attributes.yml`, with the config:

```yaml
    ambta_doctrine_encrypt.orm_subscriber:
        class: Ambta\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: [ '@ambta_doctrine_attribute_reader', '@ambta_doctrine_encrypt.encryptor' ]
        tags:
            - { name: 'doctrine.event_listener', event: 'postLoad' }
            - { name: 'doctrine.event_listener', event: 'onFlush' }
            - { name: 'doctrine.event_listener', event: 'preFlush' }
            - { name: 'doctrine.event_listener', event: 'postFlush' }
            - { name: 'doctrine.event_listener', event: 'onClear' }
```

So I decided I'd try to manually add this configuration to my services.yml, and then suddenly, it worked.

So, like I said, not sure if this is the correct solution, but I thought I'd share anyway, so it might help out someone else struggling with this.

Closing issue.
